
  

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SMSDB
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  aop:
    proxy-target-class: true
  thymeleaf:
    cache: false
    

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    vn.com.splussoftware.sms.config: DEBUG

server:
  port: 8182


#ldap-url: ldap://server.splus.com:389/cn=users,dc=splus,dc=com



